name: E2e Tenant Module

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install cli tools
        run: make tools
      - name: Run CUE test
        run: make test
      - name: Create cluster with kind
        run: make kind
      - name: Deploy tenant
        run: make apply
