name: Release Tenant module
on:
  push:
    tag: ['*'] # semver format

permissions:
  contents: read # needed for checkout
  packages: write # needed for GHCR access

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup CUE
        uses: cue-lang/setup-cue@v1.0.0-alpha.2
        with:
          version: v0.5.0
      - name: Setup Timoni
        uses: stefanprodan/timoni/actions/setup@main
        with:
          version: 0.11.1
      - name: Test instance build
        id: test
        run: make test
      - name: Push
        id: push
        run: make push
